# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Tour
    url: tour
    weight: 20
  - name: News
    url: post
    weight: 30
  - name: People
    identifier: tags
    weight: 40
  - name: group members
    parent: tags
    url: people
    weight: 40
  - name: Principal Investigators
    parent: tags
    url: tags/principal
    weight: 38
  - name: Events
    url: event
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Contact
    url: contact
    weight: 70

